spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
    maximum-pool-size: 10
  jpa:
    generate-ddl: false
    show-sql: false
    properties:
      javax:
        persistence:
          validation:
            mode: none
    database-platform: org.hibernate.dialect.H2Dialect
  freemarker:
    enabled: true
    cache: true
    prefix: default
    suffix: .ftl
  h2:
    console:
      enabled: true
      path: /h2